# Generated by Django 3.1.4 on 2021-01-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='paln',
            new_name='description',
        ),
    ]
